# services:
#   redis:
#     image: redis:latest
#     container_name: redis
#     environment:
#       - REDIS_PASSWORD=${REDIS_PASSWORD}
#       - REDIS_USER=${REDIS_USER}
#       - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
#     ports:
#       - "${REDIS_PORT}:6379"
#     volumes:
#       - ./redisdata:/data
#     networks:
#       - backend
services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - backend

volumes:
  dbdata6:

networks:
  backend:
    driver: bridge